services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutoria-backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/__pycache__/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tutoria-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env.frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    container_name: tutoria-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tutoria
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:14
    container_name: tutoria-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
