version: '3.9'

services:
    db_test:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      -"5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
  
volumes:
  pgdata_test: