"""update invite_code and student

Revision ID: af14925a24ae
Revises: 37cc951e7e26
Create Date: 2025-08-05 15:52:37.405107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af14925a24ae'
down_revision: Union[str, Sequence[str], None] = '37cc951e7e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_code', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invite_code', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite_code', type_='foreignkey')
    op.drop_column('invite_code', 'student_id')
    # ### end Alembic commands ###
