"""add fields to teacher

Revision ID: f25d5c2f7597
Revises: af14925a24ae
Create Date: 2025-08-06 14:53:29.949954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25d5c2f7597'
down_revision: Union[str, Sequence[str], None] = 'af14925a24ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'teacher',
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('NOW()'),
            nullable=False
        )
    )
    op.add_column('teacher', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('teacher', sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'is_active')
    op.drop_column('teacher', 'last_login_at')
    op.drop_column('teacher', 'created_at')
    # ### end Alembic commands ###
